[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.2.0"

[[constraint]]
  name = "github.com/ecnepsnai/logtic"
  version = "1.0.1"

[prune]
  go-tests = true
  unused-packages = true
