name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3

      - name: Set up Go
        uses: actions/setup-go@3
        with:
          go-version: 1.20.3

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
